name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Nuxt build
      run: |
        npm install yarn -g
        yarn install
        yarn build
      env:
        CI: true
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

    - name: Deploy to servers
      run: |
        mkdir ~/.ssh
        
        echo "$DEPLOYMENT_KEY" > ~/.ssh/github-deployment
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/github-deployment
        
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST rm -rf /srv/www-publish
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST mkdir /srv/www-publish

        tar --create --file=build.tar.gz --exclude=build.tar.gz --exclude=yarn.lock --verbose --gzip .
        
        scp -rp -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment build.tar.gz $SERVER_USER@$SERVER_HOST:/srv/www-publish/
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST "cd /srv/www-publish && tar --extract --gzip --file=build.tar.gz && rm build.tar.gz"

        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST rm -rf /srv/www-backup
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST mv /srv/www /srv/www-backup
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST mv /srv/www-publish /srv/www

        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_USER@$SERVER_HOST "chown -R www-data:www-data /srv/www"
      env:
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
