name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Deploy to servers
      run: |
        mkdir ~/.ssh
        echo "$DEPLOYMENT_KEY" > ~/.ssh/github-deployment
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/github-deployment
        ssh -o "StrictHostKeyChecking no" -i ~/.ssh/github-deployment $SERVER_HOST ls /srv
      env:
        DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
